"""
Aggregate community-contributed benchmark runs into COMMUNITY-BENCHMARKS.md.

Reads every ../community-benchmarks/*.json (each one an analyze.py `summary.json`,
optionally plus metadata: "contributor", "window", "note"), computes the deltas
each run can support, and writes ../COMMUNITY-BENCHMARKS.md.

Design rule (matches ROADMAP §2): no averaging away the disagreement. Every run
stays visible as its own row — including the ones where the skills made replies
*longer*. The roll-up reports the spread (min/max), not just a flattering mean.

Usage:
    python aggregate.py

No dependencies beyond the standard library. No data leaves your machine.
"""
from __future__ import annotations

import glob
import json
import statistics
from pathlib import Path

HERE = Path(__file__).resolve().parent
CB_DIR = HERE.parent / "community-benchmarks"
OUT = HERE.parent / "COMMUNITY-BENCHMARKS.md"


def pct(new, old):
    """Percent change new-vs-old, rounded to 0.1. None if old is missing/zero."""
    try:
        old = float(old)
        if old == 0:
            return None
        return round((float(new) - old) / old * 100, 1)
    except (TypeError, ValueError):
        return None


def load_runs():
    runs = []
    for path in sorted(CB_DIR.glob("*.json")):
        if path.name.startswith("_"):  # _template.json etc.
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:  # noqa: BLE001 — skip malformed, keep going
            print(f"skip {path.name}: {exc}")
            continue
        runs.append((path.stem, data))
    return runs


def run_deltas(data):
    """Return the deltas this run can support (some runs have no pre-cohort)."""
    out = {"cohort_mean": None, "cohort_p90": None, "jimat_mean": None, "n": 0}
    cohort = data.get("cohort", {}) or {}
    if "pre" in cohort and "post" in cohort:
        out["cohort_mean"] = pct(cohort["post"].get("mean_output"), cohort["pre"].get("mean_output"))
        out["cohort_p90"] = pct(cohort["post"].get("p90_output"), cohort["pre"].get("p90_output"))
    mode = data.get("mode", {}) or {}
    if "default" in mode and "jimat" in mode:
        out["jimat_mean"] = pct(mode["jimat"].get("mean_output"), mode["default"].get("mean_output"))
    # total assistant messages measured
    n = sum(int(c.get("n_messages", 0) or 0) for c in cohort.values())
    if not n:
        n = sum(int(m.get("n_messages", 0) or 0) for m in mode.values())
    out["n"] = n
    return out


def fmt(v):
    return "—" if v is None else f"{v:+.1f}%"


def build_markdown(runs):
    lines = [
        "# Community Benchmarks",
        "",
        "Real, contributed measurements of MAJI Skills — generated by "
        "[`analytics/aggregate.py`](./analytics/aggregate.py) from the "
        "`summary.json` files in [`community-benchmarks/`](./community-benchmarks).",
        "",
        "Every run is its own row. We do **not** average away disagreement: a run where "
        "the skills made replies *longer* stays visible. The point is honest data, not a "
        "flattering headline. How to contribute: "
        "[CONTRIBUTING-BENCHMARKS.md](./CONTRIBUTING-BENCHMARKS.md).",
        "",
    ]

    if not runs:
        lines += [
            "---",
            "",
            "## No contributions yet — be the first",
            "",
            "The only numbers so far are the maintainer's, in [BENCHMARKS.md](./BENCHMARKS.md) "
            "(n = 1). This file fills in as people run the pipeline on their own logs and open a PR.",
            "",
            "Run it (about two weeks of normal use), then PR your `summary.json` — "
            "**we'll publish it even if it makes the skills look bad.** That invitation is the "
            "whole point.",
            "",
        ]
        OUT.write_text("\n".join(lines), encoding="utf-8")
        print(f"{OUT.name}: 0 contributions (placeholder written)")
        return

    lines += [
        "| Contributor | Messages | Cohort mean Δ | Cohort P90 Δ | jimat vs default (mean) | Window | Note |",
        "|---|---:|---:|---:|---:|---|---|",
    ]
    cohort_means, jimat_means, total_msgs = [], [], 0
    for stem, data in runs:
        d = run_deltas(data)
        who = data.get("contributor", stem)
        window = data.get("window", data.get("skills_launch", ""))
        note = data.get("note", "")
        total_msgs += d["n"]
        if d["cohort_mean"] is not None:
            cohort_means.append(d["cohort_mean"])
        if d["jimat_mean"] is not None:
            jimat_means.append(d["jimat_mean"])
        lines.append(
            f"| {who} | {d['n']:,} | {fmt(d['cohort_mean'])} | {fmt(d['cohort_p90'])} "
            f"| {fmt(d['jimat_mean'])} | {window} | {note} |"
        )

    lines += ["", "## Roll-up", "", f"- **Contributors:** {len(runs)}", f"- **Total messages:** {total_msgs:,}"]
    if cohort_means:
        lines.append(
            f"- **Cohort mean Δ:** median {statistics.median(cohort_means):+.1f}% · "
            f"spread {min(cohort_means):+.1f}% … {max(cohort_means):+.1f}% (n={len(cohort_means)})"
        )
    if jimat_means:
        lines.append(
            f"- **jimat vs default (mean):** median {statistics.median(jimat_means):+.1f}% · "
            f"spread {min(jimat_means):+.1f}% … {max(jimat_means):+.1f}% (n={len(jimat_means)})"
        )
    lines += [
        "",
        "*Spread, not just the median — a single flattering average would defeat the purpose. "
        "Contributed numbers differ by workload mix; that's expected, not a bug.*",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.name}: {len(runs)} contribution(s), {total_msgs:,} messages")


if __name__ == "__main__":
    build_markdown(load_runs())
