#!/usr/bin/env node
// Regenerate the skill index inside AGENTS.md (between the index markers) from each SKILL.md frontmatter.
// Usage: node scripts/build-index.mjs [--check]   (--check exits 1 if AGENTS.md is out of date; used in CI)
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { ROOT, findSkills, parse } from "./lint-skills.mjs"

const HUB = join(ROOT, "AGENTS.md")
const ORDER = [
  ["discipline", "Discipline (apply first)"],
  ["plan", "Plan and run work"],
  ["dev", "Code"],
  ["ship", "Ship and maintain"],
  ["product", "Product and UI"],
  ["content", "Content and media"],
  ["business", "Documents and sales"],
  ["data", "Data"],
  ["writing", "Writing"],
  ["meta", "Setup and learning"],
]

const firstSentence = (d) => {
  const s = d.match(/^(.+?\.)(\s|$)/)?.[1] ?? d
  if (s.length <= 160) return s
  const cut = s.slice(0, 157)
  return cut.slice(0, cut.lastIndexOf(" ")).replace(/[,:;(]+$/, "") + "..."
}
// Personal my-* skills are discovered by the agents directly and never listed in the shared hub.
const skills = findSkills().map((f) => parse(readFileSync(f, "utf8"))).filter(Boolean).map((d) => d.fm).filter((s) => !s.name.startsWith("my-"))
const lines = []
for (const [cat, title] of ORDER) {
  const group = skills.filter((s) => s.metadata?.category === cat).sort((a, b) => a.name.localeCompare(b.name))
  if (!group.length) continue
  lines.push(`\n**${title}**`)
  for (const s of group) lines.push(`- \`${s.name}\`${s.metadata.tier === "experimental" ? " (experimental)" : ""}: ${firstSentence(s.description)}`)
}
const block = `<!-- index:start (generated by scripts/build-index.mjs, do not edit by hand) -->\n${lines.join("\n").trim()}\n<!-- index:end -->`
const hub = readFileSync(HUB, "utf8")
const next = hub.replace(/<!-- index:start[\s\S]*?<!-- index:end -->/, block)
if (process.argv.includes("--check")) {
  if (next !== hub) { console.log("AGENTS.md index is out of date: run node scripts/build-index.mjs"); process.exit(1) }
  console.log("index ok")
} else {
  writeFileSync(HUB, next)
  console.log(`index: ${skills.length} skills, AGENTS.md ${Buffer.byteLength(next)} bytes`)
}
